apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com/cogitok/helm-charts.git'
    path: helm-charts/airflow
    targetRevision: 8.8.0
    helm:
      valueFiles:
        - sample-values-KubernetesExecutor.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true