apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com/cogitok/helm-charts.git'
    path: helm-charts/airflow_official
    targetRevision: 1.11.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflowsec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true